server:
  port: 8761

spring:
  application:
    name: study-eureka

eureka:
  instance:
    instance-id: eureka
    #自我保护时间：上次心跳距离时间
    lease-expiration-duration-in-seconds: 90
    #健康心跳
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
#    hostname: ${spring.application.name}-${server.port} #eureka服务端的实例名称
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #集群指向其它eureka
      defaultZone: http://${spring.application.name}:${server.port}/eureka/
      #单机就是自己
      #defaultZone: http://study-eureka:8761/eureka/
  server:
    #关闭自我保护机制，保证不可用服务被及时踢除
    #清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 2000
    enable-self-preservation: false